FROM node:latest as builder
WORKDIR /app
RUN npm install -g @angular/cli
COPY ./src/package*.json .
RUN npm install
COPY ./src .
RUN ng build --configuration=production
FROM nginx:alpine
COPY --from=builder /app/dist/store /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]