version: '3'
services:
  database:
    image: postgres:latest
    restart: always
    container_name: webshop
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '5433:5432'